# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: openkanso-agent

builds:
  - id: openkanso-agent
    main: ./cmd/agent
    binary: okagent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - "-s -w"

archives:
  - formats:
      - binary
    name_template: "okagent"

checksum:
  name_template: "checksums.txt"
